apiVersion: v1
kind: Pod
metadata:
  name: mongodb-backend
  labels:
    app: mongodb-backend
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: tier
                operator: In
                values:
                  - backend
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
