apiVersion: v1
kind: Pod
metadata:
  name: spark-driver-template
  labels:
    app.kubernetes.io/component: driver
    tier: spark-snowflake-driver
spec:
  containers:
    - name: spark-kubernetes-driver
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: app-config
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret
