FROM apache/airflow:2.8.1-python3.10

USER root
# Install system packages if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Amazon provider package for EMR on EKS operators and AWS SDKs
RUN pip install --no-cache-dir \
    apache-airflow-providers-amazon>=8.15.0 \
    boto3>=1.34.0
