apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-replicaset
  labels:
    app: flask-rs
spec:
  # Maintain exactly 3 running pod instances of our application
  replicas: 6
  selector:
    matchLabels:
      app: flask-rs-pod
  template:
    metadata:
      labels:
        app: flask-rs-pod
    spec:
      containers:
        - name: flask-container
          image: technoavengers/primal-python
